### ISSUE TITLE
Question about Singling

### ISSUE THREAD

**Issue by DonKoko** [fearedbliss/Cactus#10]
Just found this repo because i was looking for RWM and found this in a forum somewhere. From what I understand Singling has RWM included. Would it work for 1.14d?

**Comment by fearedbliss** [comment]
Hey,

The 1.13d and 1.14d patches are exactly the same so in this case using the Singling 1.13d patch would work for you in 1.14d, however the patch may contain other changes I have made. Check the notes.

**Comment by DonKoko** [comment]
Thanks for the info. I saw there was a video so now its also a bit more clear. Thanks for the great work
