### ISSUE TITLE
Different mods for each version

### ISSUE THREAD

**Issue by sharpwg1337** [fearedbliss/Cactus#10]
Is there any possible way to play using Cactus and 3 different versions all with different mods, files, and launchers (1.00, 1.09b, and 1.13d for example)? 

For example 1.00 I need to use Game.exe, but 1.09b and 1.13d I need to use Plugy.exe, however I need a different Plugy setting configuration and launch parameters for both 1.09b and 1.13d, and obviously per directory you only have one Plugy settings file so I can't separate that need out. 

There are also some other dll-less mods that need to be installed to the root Diablo II directory (installing the files to the respective Platforms version folder does not work, and are version specific so installing the files to the root directory makes it only work for one version). 

Am I out of luck with Cactus and will need a separate install folder for each version or is there any possible way to make this work using Cactus?

**Comment by fearedbliss** [comment]
Yes this is possible and the approach you mentioned is the correct way to do it (all mod specific files need to be in their platform directory). Essentially every platform is fully isolated from each other and only share the core cactus files and mpqs. You can take a look at different mods that I’ve ported (51 of them to be specific) and are listed in the Cactus Ports Collection. They are all on different versions and are either using PlugY or their own mod systems.
