### ISSUE TITLE
Running multiple instances

### ISSUE THREAD

**Issue by m0ssse** [fearedbliss/Cactus#13]
Hi,
I recently installed Cactus on a new PC but for some reason I am unable to run multiple copies of the same version of the game, namely 1.00. On my old laptop, I ran 8 copies for more experience and muling but for some reason when I try to launch a second copy, I get an error saying that only one copy can run at a time. I tried uninstalling and reinstalling the game and rerunning the MPQfixer but the problem still persists.

**Comment by fearedbliss** [comment]
You game normally allows you to only run one copy. You need to install the Singling modifications for version 1.00 in order for it to work.
