### ISSUE TITLE
Issue adding and running a platform

### ISSUE THREAD

**Issue by Giles-Billenness** [fearedbliss/Cactus#15]
Just installed and tried to add a platform and run it as specified in the readme (dropping in the files + running the mpq fix, etc).
![image](https://user-images.githubusercontent.com/56511720/91666212-ebf66480-eaf2-11ea-8a3f-73bd5b3159df.png)

![image](https://user-images.githubusercontent.com/56511720/91666233-0f211400-eaf3-11ea-9f33-26d2ae8b2564.png)

the path given was: "B:\Diablo II - cactus\Platforms\1.14d"
Is this the issue?

**Comment by fearedbliss** [comment]
Yes it is, that's incorrect.

The path is the Path to the executable of the executable you want to launch in the root of your diablo 2 folder, not in the platform directory.

The correct path would be:

`B:\Diablo II - cactus\Game.exe`.

Let me know if that fixes it for you.

**Comment by fearedbliss** [comment]
This is also what's written in the Cactus README Instructions:


`
Enter the path to the executable you want to launch in your Diablo II root folder. Cactus copies all of the files from the Platforms/[NAME] folder to the Diablo II root folder, so most of your entries will have identical paths (Example: D:\Games\Diablo II\Game.exe).
`

**Comment by Giles-Billenness** [comment]
![image](https://user-images.githubusercontent.com/56511720/91666382-24e30900-eaf4-11ea-9715-059d349726d3.png)
Getting this when making the change:
![image](https://user-images.githubusercontent.com/56511720/91666391-37f5d900-eaf4-11ea-96fb-65573d8a2582.png)

**Comment by fearedbliss** [comment]
Yup. Those are the correct instructions. You have other entries that are not the same as the root:

`B:\Diablo II - cactus\`

Once you have a root set, all other entries need to match that root exactly. The only thing allowed to be changed at that point is the executable: `Game.exe`, `Diablo II.exe`, `Alpaca.exe` for example.

**Comment by Giles-Billenness** [comment]
Ah!, it was my other incorrect platform add.
