### ISSUE TITLE
Shaders Not Working

### ISSUE THREAD

**Issue by whipowill** [fearedbliss/Cactus#16]
I have the ddraw working but whatever shader I specify in the INI file won't load at all.  I don't know if it's a path issue to the file location or if it's a Wine issue.  I'm using Wine on Mac with the game in windowed mode.  Any ideas?

**Comment by fearedbliss** [comment]
No idea. I've tested this on Windows and Linux and can confirm it's working here.

**Comment by FunkyFr3sh** [comment]
It's a macOS specific problem, by default there's only a opengl 2.1 profile available but the shaders require opengl 3.0.

Will put it on my to-do list but I don't have a mac so it's not possible for me to test it though
