### ISSUE TITLE
Cactus & Wine - Black Screen?

### ISSUE THREAD

**Issue by track02** [fearedbliss/Cactus#17]
Perhaps a long shot but have you had any issues running Cactus under Wine?

The application launches but visually appears as an entirely black window with buttons/text appearing when I hover over them, I've tried installing dotnet46 via winetricks but no luck, so wondering if I'm missing something (feel it may be more of a Wine config issue rather than Cactus but searching hasn't turned up much)

No issues apart from that, I can play the game just fine if I run the .exe directly but it'd be great to be able to manage everything via Cactus if possible

**Comment by fearedbliss** [comment]
Cactus was designed exclusively as a Windows only application. Thus there is no support for Wine.
