### ISSUE TITLE
PlugY installation guide

### ISSUE THREAD

**Issue by shine60vn** [fearedbliss/Cactus#2]
Hi @fearedbliss , thanks for your time to make this great tool.

The README is saying that the switcher supports PlugY 11.02 but I cannot get it to work. I use PlugY installer (.exe file which is recommended on PlugY website). When I open PlugY.exe, nothing happens. Could you please tell me the correct way to install PlugY with Cactus? 

Many thanks.

**Comment by fearedbliss** [comment]
Don't use the installer, use the plugy zip file and just throw all of the files into the platform folder for the version of the game that will use it. The Cactus read me has a link to a video that shows you how to set it up. I set up Plugy in there as well.

**Comment by shine60vn** [comment]
Thanks @fearedbliss , I'll try your suggestion.

**Comment by seantcanavan** [comment]
Hey @fearedbliss. I noticed that if you run `Cactus.exe`. from your install folder without administrator privileges then Plugy doesn't work.

Here's what worked for me:

* Download Plugy install files as a zip from http://plugy.free.fr/en/index.html
* Unzip the zip folder
* Copy all the files to the right Platforms folder. `C:\Program Files (x86)\Diablo II\Platforms\1.13d` for me.
* Add a new entry to `Catcus.exe` with `C:\Program Files (x86)\Diablo II\PlugY.exe` as the target and `-w -ns -3dfx` as the Flags.
* Run `Catcus.exe` as administrator
* Diablo 1.13d with Plugy support starts correctly

If `Cactus.exe` is not started with Administrator privileges, then Cactus doesn't do anything when you hit `Launch` after installing Plugy
