### ISSUE TITLE
Cactus does not close properly

### ISSUE THREAD

**Issue by CaptainCosmotic** [fearedbliss/Cactus#20]
If I run a game and close cactus afterwards cactus remains active in the background. It shows an error message with: "only one instance of Cactus is allowed!" if I want to run it again and I have to close the program with the task manager.
*Edit* I use Windows 10

**Comment by fearedbliss** [comment]
There is nothing in Cactus that would cause it to hang so it isn't a Cactus bug. The hanging issues come from D2/ and Glide. This was documented in the README-RENDERERS documentation. Specifically: https://github.com/fearedbliss/Cactus/blob/master/README-RENDERERS.md#fixing-the-hanging-diablo-ii-process-in-windows-10-build-1903-upon-exit
