### ISSUE TITLE
Changing from 1.14b to 1.13d

### ISSUE THREAD

**Issue by mokargas** [fearedbliss/Cactus#4]
When changing from 1.14b (fresh install) to 1.13d using the supplied files under `Platforms/1.13d`, I get the error `d2data.mpq` corrupt.

I figured this meant I had to run the WinMPQ bat file fix, which succeeded on the copy of the 1.14 version mpq files I placed under `Platforms\1.13d`. However, I get the same error.

Also tried with 1.14d with Singling with the same issue (Windows 10). Do I have the process for going back incorrect?

**Comment by fearedbliss** [comment]
You have to run the MPQ fix in the root of the Diablo 2 directory alongside all of your MPQs. Watch the video I made about this. Link is in the readme.

**Comment by fearedbliss** [comment]
Also this issue was already asked before

https://github.com/fearedbliss/Cactus/issues/1

**Comment by seantcanavan** [comment]
@fearedbliss Your `singling` project and the setup video links you reference in #1 [here](https://github.com/fearedbliss/Cactus/issues/1#issuecomment-391075112) are both not working unfortunately.
