### ISSUE TITLE
Windows 10 (1903) issues

### ISSUE THREAD

**Issue by k3lt** [fearedbliss/Cactus#5]
Hi, there are some issues with Cactus using Windows 10 1903 build.
Everytime you run Cactus and close it the process is actually not killed, you have manually go to task manager and kill it there.
Same with Diablo II that was launched with Cactus, if you exit the game the process is still running and you are unable to run different game version. (another process related to another game mode/version is running error)
So again, you have to kill the game manually in task manager.

It only happens if i run the game with Cactus, if i just launch Diablo II with Game.exe the process is killed after i exit the game.

**Comment by fearedbliss** [comment]
I've been running Windows 10 1903 for years and I don't have this issue (It isn't a Cactus bug). This means that your Diablo II is not closing properly/running in the background for whatever reason, thus Cactus won't allow you to switch versions. You need to figure out why Diablo II isn't properly closing.

**Comment by k3lt** [comment]
My Diablo II is closing properly when i'm running it without Cactus.

**Comment by k3lt** [comment]
Ok actually it's issue with bundled Glide Wrapper not Cactus, Glide Wrapper is causing Game.exe process deadlock, when running the game without "-3dfx" process ends properly.
