### ISSUE TITLE
Succulent: is there a way to disable drop as /players 8 emulation? 

### ISSUE THREAD

**Issue by gladorange** [fearedbliss/Cactus#6]
Hi,
Drop for 8 players makes Countess runs less effective than single player.
Is there a way to disable it in Succulent?

**Comment by fearedbliss** [comment]
Nope. Succulent is provided as is.

**Comment by fearedbliss** [comment]
Also I forgot to mention, it doesn't make it less effective, it makes it more effective since countess is dropping more items, which means more chances for the runes to drop. Also remember succulent rune drops can go up to Zod depending on difficulty.

**Comment by gladorange** [comment]
According to this page https://diablo2.diablowiki.net/The_Countess#Rune_Drop_Specials

Her Treasure Classes are uniquely modified, and as a result the odds of her dropping multiple runes are actually increased when there is only one player in the game. (Even though she'll never drop more than two items, her rune drops come from special treasure class sequences that are accessed if the game doesn't think she should drop other items. Since she's more likely to roll to drop additional items when more players are in the game, even though her drop is hardcapped at two magical items, this cuts down on her odds of dropping a rune.)

**Comment by fearedbliss** [comment]
Interesting, although I don't know how true that is in practice since from my testing I was able to drop even three high runes sometimes from her (in addition to other items). Regardless, the players always 8 is set globally and the countess is not important enough for me to add exception code just for this.

**Comment by fearedbliss** [comment]
@gladorange The latest Succulent no longer has /players 8 drop amounts on by default since I've increased the global item drop rates. It also includes infinite respecs to encourage experimentation. This may be of interest to you.
