### ISSUE TITLE
Documentation - flags?

### ISSUE THREAD

**Issue by agris-codes** [fearedbliss/Cactus#7]
Hello, I'm in the process of setting up my D2 environment and I cannot find an enumeration of all flags. For example, in your quick setup instructions for Windows, you indicate "-ns" is a potential flag. What is that? There doesn't appear to be a list of all flags anywhere. Similarly, in the ddraw readme there are some flags referenced, but no comprehensive list that I can find.

In the same vein of documentation, I imagine a lot of people who are looking for a "vanilla+" experience and using Cactus would appreciate some guidance for how to enable widescreen internal rendering using 3rd party plugins. If it is possible, and that is an assumption on my end, it seems like an obvious "how to" to add to the project documentation. 

Apologies for posting this as an issue, as it is most definitely not. It is something for discussion, but as discussions are not enabled for this repo, I'm using the best tool at hand.

Thanks.

**Comment by fearedbliss** [comment]
This is not necessary. The flags are not Cactus specific but rather the standard Diablo II flags that have existed for the past 20 years and easily found online.

https://diablo2.diablowiki.net/Game_commands#Full_List_of_Target_Line_Commands

**Comment by agris-codes** [comment]
Feel free to link the word "flags" with that url in your documentation.
