### ISSUE TITLE
Running mpq fixer in admin gives me error loading from file 

### ISSUE THREAD

**Issue by suxel33** [fearedbliss/Cactus#8]
I get regsvr42 is not recognized as an internal or external command whenever I try to run the bat file. I am on blizzard install v 1.14d.
![cmd_3dOsdaNA6D](https://user-images.githubusercontent.com/19918635/214202077-1c22b230-a73e-420a-8804-31c4af4f574c.png)

**Comment by fearedbliss** [comment]
Are you running it as administrator? Also what Windows version you are on? It works on Windows 7 and 10 64 bit.

**Comment by fearedbliss** [comment]
FYI: If you are running your terminal in Admin mode, it should say "Administrator:" at the top left of the window.

**Comment by fearedbliss** [comment]
Closed due to inactivity and since I'm not experiencing this issue.
