### ISSUE TITLE
Custom save path

### ISSUE THREAD

**Issue by sharpwg1337** [fearedbliss/Cactus#9]
I would like to change the save path that Cactus is setting from the D2 install directory to my google drive (G:). I can't seem to do this, or am I missing something obvious? I can see the save path set in registry but changing it is useless as it just reverts back to the D2 install folder whenever I launch through Cactus. Is there no way to do this with Cactus?

**Comment by fearedbliss** [comment]
That’s correct. This is not a setting that is possible to change, and I’m not interested in changing that. The backup feature should be used to automatically backup the Saves directory (alongside any other important documents) to a directory of your choosing. The backup directory is user modifiable.
