### ISSUE TITLE
Null pointer exception on launch.

### ISSUE THREAD

**Issue by jeffsvajlenko** [fearedbliss/Cactus#9]
When trying to launch 1.13d I get the following error:

![image](https://user-images.githubusercontent.com/2321033/67256800-c366fe00-f43d-11e9-9b5e-32959ebfc377.png)

Is cactus supported when the install version is 1.14d, but I am trying to run an older version?

**Comment by fearedbliss** [comment]
Yup, all versions 1.00 - 1.14d are fully supported. There have been no new releases to Cactus for many months and the application is stable and working. You'll need to see what is going on on your machine in order to fix the issue.

**Comment by jeffsvajlenko** [comment]
Oops!  Reading comprehension failure :).  Realized my mistake when I was debugging and came back to close.

![image](https://user-images.githubusercontent.com/2321033/67258460-9585b780-f445-11e9-8815-c741627635d3.png)

Thanks for making this software, and your fast response!

**Comment by fearedbliss** [comment]
Haha np! Have fun.
